cmake_minimum_required(VERSION 3.30)
project(Prog)

set(CMAKE_CXX_STANDARD 20)

add_executable(BT_BST III-god_polugodie_1/BT_BST.cpp)
add_executable(n_queens III-god_polugodie_2/brute_force/n_queens.cpp)
add_executable(compress_decompress III-god_polugodie_2/file_work/compress_decompress.cpp)
add_executable(dijkstra III-god_polugodie_2/greedy/dijkstra.cpp)
